In [4]:
# Support Vector Machine (SVM)

# Importing the libraries
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('datasets/HR_comma_sep.csv')
X = dataset.iloc[:,[0,1,2,3,4,5,7,9]].values
y = dataset.iloc[:,6].values 

from sklearn.preprocessing import LabelEncoder, StandardScaler
labelencoder_X = LabelEncoder()
X[:,7] = labelencoder_X.fit_transform(X[:,7])

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,salary
0,0.38,0.53,2,157,3,0,0,low
1,0.80,0.86,5,262,6,0,0,medium
2,0.11,0.88,7,272,4,0,0,medium
3,0.72,0.87,5,223,5,0,0,low
4,0.37,0.52,2,159,3,0,0,low
5,0.41,0.50,2,153,3,0,0,low
6,0.10,0.77,6,247,4,0,0,low
7,0.92,0.85,5,259,5,0,0,low
8,0.89,1.00,5,224,5,0,0,low
9,0.42,0.53,2,142,3,0,0,low
10,0.45,0.54,2,135,3,0,0,low
11,0.11,0.81,6,305,4,0,0,low
12,0.84,0.92,4,234,5,0,0,low
13,0.41,0.55,2,148,3,0,0,low
14,0.36,0.56,2,137,3,0,0,low
15,0.38,0.54,2,143,3,0,0,low
16,0.45,0.47,2,160,3,0,0,low
17,0.78,0.99,4,255,6,0,0,low
18,0.45,0.51,2,160,3,1,1,low
19,0.76,0.89,5,262,5,0,0,low
20,0.11,0.83,6,282,4,0,0,low
21,0.38,0.55,2,147,3,0,0,low
22,0.09,0.95,6,304,4,0,0,low
23,0.46,0.57,2,139,3,0,0,low
24,0.40,0.53,2,158,3,0,0,low
25,0.89,0.92,5,242,5,0,0,low
26,0.82,0.87,4,239,5,0,0,low
27,0.40,0.49,2,135,3,0,0,low
28,0.41,0.46,2,128,3,0,0,low
29,0.38,0.50,2,132,3,0,0,low
...,...,...,...,...,...,...,...,...
14969,0.43,0.46,2,157,3,0,0,medium
14970,0.78,0.93,4,225,5,0,0,medium
14971,0.39,0.45,2,140,3,0,0,medium
14972,0.11,0.97,6,310,4,0,0,medium
14973,0.36,0.52,2,143,3,0,0,medium
14974,0.36,0.54,2,153,3,0,0,medium
14975,0.10,0.79,7,310,4,0,0,medium
14976,0.40,0.47,2,136,3,0,0,medium
14977,0.81,0.85,4,251,6,0,0,medium
14978,0.40,0.47,2,144,3,0,0,medium
14979,0.09,0.93,6,296,4,0,0,medium
14980,0.76,0.89,5,238,5,0,0,high
14981,0.73,0.93,5,162,4,0,0,low
14982,0.38,0.49,2,137,3,0,0,medium
14983,0.72,0.84,5,257,5,0,0,medium
14984,0.40,0.56,2,148,3,0,0,medium
14985,0.91,0.99,5,254,5,0,0,medium
14986,0.85,0.85,4,247,6,0,0,low
14987,0.90,0.70,5,206,4,0,0,low
14988,0.46,0.55,2,145,3,0,0,low
14989,0.43,0.57,2,159,3,1,0,low
14990,0.89,0.88,5,228,5,1,0,low
14991,0.09,0.81,6,257,4,0,0,low
14992,0.40,0.48,2,155,3,0,0,low
14993,0.76,0.83,6,293,6,0,0,low
14994,0.40,0.57,2,151,3,0,0,low
14995,0.37,0.48,2,160,3,0,0,low
14996,0.37,0.53,2,143,3,0,0,low
14997,0.11,0.96,6,280,4,0,0,low
14998,0.37,0.52,2,158,3,0,0,low

In [6]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [51]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(C=10, kernel='rbf', gamma=0.5)
classifier.fit(X_train, y_train)

In [52]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [53]:
#Calculating Accuracy
def evaluate_on_test_data(model=None) :
    predictions = classifier.predict(X_test)
    correct_classifications = 0
    for i in range(len(y_test)) :
        if predictions[i] == y_test[i] :
            correct_classifications += 1
    accuracy = 100*correct_classifications/len(y_test)
    return accuracy 
acc = evaluate_on_test_data(classifier)

In [54]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [55]:
def plot_coefficients(classifier, feature_names, top_features=4):
    coef = classifier.coef_.ravel()
    top_positive_coefficients = np.argsort(coef)[-top_features:]
    top_negative_coefficients = np.argsort(coef)[:top_features]
    top_coefficients = np.hstack([top_negative_coefficients, top_positive_coefficients])
    # create plot
    plt.figure(figsize=(15, 5))
    colors = ['red' if c < 0 else 'blue' for c in coef[top_coefficients]]
    plt.bar(np.arange(2 * top_features), coef[top_coefficients], color=colors)
    feature_names = np.array(feature_names)
    plt.xticks(np.arange(1, 1 + 2 * top_features), feature_names[top_coefficients], rotation=60, ha='right')
    plt.show()

In [56]:
cv = CountVectorizer()
cv.fit(dataset)
print(len(cv.vocabulary_))
print(cv.get_feature_names())

10
['average_montly_hours', 'last_evaluation', 'left', 'number_project', 'promotion_last_5years', 'salary', 'sales', 'satisfaction_level', 'time_spend_company', 'work_accident']

In [57]:
# plot_coefficients(classifier, cv.get_feature_names())

In [58]:
print(acc)

97.6